name: 'Stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # PRs
          stale-pr-message: 'This PR is stale because it has been open 120 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          days-before-pr-stale: 120
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          days-before-pr-close: 10
          exempt-all-pr-assignees: true
          exempt-pr-labels: 'awaiting-approval,work-in-progress'
          stale-pr-label: 'stale'
          # Issues
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          days-before-issue-stale: 60
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          days-before-issue-close: 5
          exempt-issue-assignees: true
          exempt-issue-labels: 'awaiting-approval,work-in-progress'
          stale-issue-label: 'stale'
